# Copyright (C) 2024 Roberto Rossini (roberros@uio.no)
# SPDX-License-Identifier: MIT

name: CI

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - ".github/workflows/pip.yml"
      - "src/**"
      - "test/**"
      - "CMakeLists.txt"
      - "pyproject.toml"

  pull_request:
    paths:
      - ".github/workflows/pip.yml"
      - "src/**"
      - "test/**"
      - "CMakeLists.txt"
      - "pyproject.toml"

# https://stackoverflow.com/a/72408109
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

jobs:
  build-project:
    strategy:
      fail-fast: false
      matrix:
        platform: [windows-latest, macos-latest, ubuntu-latest]
        python-version: ["3.9", "3.13"]

    runs-on: ${{ matrix.platform }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Add requirements
        run: python -m pip install --upgrade wheel setuptools

      - name: Build and install
        run: pip install --verbose '.[test]'

      - name: Test
        run: python -m pytest test -v
